name: Publish to npm

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Ensures HEAD~1 is available

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Read current and previous versions
        id: version_check
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          PREV_VERSION=$(git show HEAD~1:package.json | jq -r .version)
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "previous=$PREV_VERSION" >> $GITHUB_OUTPUT

      - name: Skip if version did not change
        if: steps.version_check.outputs.current == steps.version_check.outputs.previous
        run: |
          echo "Version unchanged. Skipping publish."
          exit 0

      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile

      - name: Build with Bun
        run: bun run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
